#!/usr/bin/env python3
# Mupen64Plus PS5: builds frontend's game-name table (CRC1 <tab> name) from mupen64plus-core's ROM catalog.
#
# N64 cartridges carry two checksums in their header (CRC1/CRC2 at 0x10/0x14), and mupen64plus.ini lists
# them with each ROM's GoodN64 name ("Super Mario 64 (U) [!]"). The shelf names games and finds their
# covers (libretro-thumbnails, No-Intro names) from this table, so the GoodN64 names are turned into
# No-Intro style ones: dump tags ([!] [b1] [t1] ...) dropped, country codes spelled out ((U) -> (USA)),
# (V1.1) -> (Rev 1). It is not a full No-Intro table; files already named the No-Intro way are used as is.
#
#   make_n64db.py mupen64plus.ini out.tsv
#
# SPDX-License-Identifier: MIT
import re
import sys

COUNTRIES = {
    "U": "USA", "E": "Europe", "J": "Japan", "JU": "Japan, USA", "UE": "USA, Europe", "JUE": "World",
    "W": "World", "F": "France", "G": "Germany", "I": "Italy", "S": "Spain", "A": "Australia",
    "B": "Brazil", "K": "Korea", "C": "China", "Ch": "China", "N": "Netherlands", "Sw": "Sweden",
    "FC": "Canada", "GR": "Greece", "HK": "Hong Kong", "D": "Netherlands", "PD": "PD",
}


def convert(good):
    name = re.sub(r"\s*\[[^\]]*\]", "", good)  # [!] [b1] [t1] [T+Spa] ...
    name = re.sub(r"\s*\(M\d+\)", "", name)  # (M3): number of languages
    name = re.sub(r"\s*\((?:PAL|NTSC|PAL-NTSC|V64-PAL)[^)]*\)", "", name)

    def country(m):
        code = m.group(1)
        return " (%s)" % COUNTRIES[code] if code in COUNTRIES else m.group(0)

    name = re.sub(r" \(([A-Za-z]{1,3})\)", country, name)
    name = re.sub(r" \(V1\.0\)", "", name)
    name = re.sub(r" \(V1\.(\d)\)", lambda m: " (Rev %s)" % m.group(1), name)
    return re.sub(r"\s+", " ", name).strip()


def rank(good):
    # verified dumps first, then plain names, then bad/overdumps/hacks/trainers/translations
    if "[!]" in good:
        return 0
    if "[" not in good:
        return 1
    return 2


def main():
    src, dst = sys.argv[1], sys.argv[2]
    best = {}
    good = crc = None
    with open(src, encoding="latin-1") as f:
        for line in f:
            line = line.strip()
            if line.startswith("["):
                good = crc = None
            elif line.startswith("GoodName="):
                good = line[9:]
            elif line.startswith("CRC="):
                crc = line[4:].split()[0].upper()
            if good and crc and re.fullmatch(r"[0-9A-F]{8}", crc):
                r = rank(good)
                if crc not in best or r < best[crc][0]:
                    best[crc] = (r, convert(good))
                good = crc = None
    with open(dst, "w", encoding="utf-8", newline="\n") as out:
        out.write("# CRC1\tname (generated by tools/make_n64db.py from mupen64plus.ini)\n")
        for crc in sorted(best):
            out.write("%s\t%s\n" % (crc, best[crc][1]))
    print("%s: %d games" % (dst, len(best)))


if __name__ == "__main__":
    main()
